# Generated by Django 5.2.11 on 2026-02-18 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assembly',
            new_name='estimating__organiz_986649_idx',
            old_name='estimating_assembly_org_created',
        ),
        migrations.RenameIndex(
            model_name='assembly',
            new_name='estimating__organiz_5f55b6_idx',
            old_name='estimating_assembly_org_active',
        ),
        migrations.RenameIndex(
            model_name='assemblyitem',
            new_name='estimating__assembl_5418e9_idx',
            old_name='estimating_assemblyitem_assembly_order',
        ),
        migrations.RenameIndex(
            model_name='costcode',
            new_name='estimating__organiz_d3dfec_idx',
            old_name='estimating_costcode_org_division',
        ),
        migrations.RenameIndex(
            model_name='costcode',
            new_name='estimating__organiz_dc4d0f_idx',
            old_name='estimating_costcode_org_code',
        ),
        migrations.RenameIndex(
            model_name='costcode',
            new_name='estimating__organiz_bf6abb_idx',
            old_name='estimating_costcode_org_active',
        ),
        migrations.RenameIndex(
            model_name='costitem',
            new_name='estimating__organiz_7c1e8c_idx',
            old_name='estimating_costitem_org_costcode',
        ),
        migrations.RenameIndex(
            model_name='costitem',
            new_name='estimating__organiz_cf2a5c_idx',
            old_name='estimating_costitem_org_created',
        ),
        migrations.RenameIndex(
            model_name='costitem',
            new_name='estimating__organiz_a421e7_idx',
            old_name='estimating_costitem_org_active',
        ),
        migrations.RenameIndex(
            model_name='estimate',
            new_name='estimating__organiz_3a0f2f_idx',
            old_name='estimating_estimate_org_status',
        ),
        migrations.RenameIndex(
            model_name='estimate',
            new_name='estimating__organiz_75dc6f_idx',
            old_name='estimating_estimate_org_project',
        ),
        migrations.RenameIndex(
            model_name='estimate',
            new_name='estimating__organiz_360d6f_idx',
            old_name='estimating_estimate_org_lead',
        ),
        migrations.RenameIndex(
            model_name='estimate',
            new_name='estimating__organiz_4d9cb0_idx',
            old_name='estimating_estimate_org_created',
        ),
        migrations.RenameIndex(
            model_name='estimatelineitem',
            new_name='estimating__section_96c8f5_idx',
            old_name='estimating_lineitem_section_order',
        ),
        migrations.RenameIndex(
            model_name='estimatelineitem',
            new_name='estimating__cost_it_e22a53_idx',
            old_name='estimating_lineitem_costitem',
        ),
        migrations.RenameIndex(
            model_name='estimatelineitem',
            new_name='estimating__assembl_4fe6e2_idx',
            old_name='estimating_lineitem_assembly',
        ),
        migrations.RenameIndex(
            model_name='estimatesection',
            new_name='estimating__estimat_22fa43_idx',
            old_name='estimating_section_estimate_order',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='estimating__organiz_13a801_idx',
            old_name='estimating_proposal_org_status',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='estimating__organiz_f570ee_idx',
            old_name='estimating_proposal_org_client',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='estimating__public__bfbff3_idx',
            old_name='estimating_proposal_token',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='estimating__organiz_e238d7_idx',
            old_name='estimating_proposal_org_sent',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='estimating__organiz_defa63_idx',
            old_name='estimating_proposal_org_signed',
        ),
        migrations.RenameIndex(
            model_name='proposaltemplate',
            new_name='estimating__organiz_5b588c_idx',
            old_name='estimating_proposaltemplate_org_default',
        ),
        migrations.AddField(
            model_name='assembly',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assemblyitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimatesection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
