# Generated by Django 5.2.12 on 2026-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0002_rename_estimating_assembly_org_created_estimating__organiz_986649_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3),
        ),
    ]
