# Generated by Django 5.2.12 on 2026-03-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_organizationbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationbranding',
            name='company_name_override',
            field=models.CharField(blank=True, help_text='Override org name in UI (e.g., for white-label deployments)', max_length=200),
        ),
    ]
