# Generated by Django 5.2.11 on 2026-02-18 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_ops', '0002_initial'),
        ('projects', '0003_rename_projects_ai_org_resolved_idx_projects_ac_organiz_c100fb_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('folder_type', models.CharField(choices=[('GENERAL', 'General'), ('PLANS', 'Plans & Drawings'), ('PERMITS', 'Permits'), ('CONTRACTS', 'Contracts'), ('SUBMITTALS', 'Submittals'), ('RFI', 'RFIs'), ('PHOTOS', 'Photos'), ('SAFETY', 'Safety'), ('WARRANTY', 'Warranty')], default='GENERAL', max_length=20)),
                ('access_level', models.CharField(choices=[('ALL_TEAM', 'All Team Members'), ('MANAGERS_ONLY', 'Managers Only'), ('ADMIN_ONLY', 'Admin Only'), ('CLIENT_VISIBLE', 'Client Visible')], default='ALL_TEAM', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
                ('project', models.ForeignKey(blank=True, help_text='Org-level folder if null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='projects.project')),
            ],
            options={
                'verbose_name': 'Document Folder',
                'verbose_name_plural': 'Document Folders',
                'db_table': 'documents_folder',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file_key', models.CharField(help_text='S3 object key', max_length=1000)),
                ('file_name', models.CharField(help_text='Original filename', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='Bytes')),
                ('content_type', models.CharField(blank=True, help_text='MIME type', max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('is_current_version', models.BooleanField(db_index=True, default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('requires_acknowledgment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='documents.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_key', models.CharField(help_text='S3 object key', max_length=1000)),
                ('thumbnail_key', models.CharField(blank=True, help_text='S3 key for 400px thumbnail', max_length=1000)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='image/jpeg', max_length=100)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('taken_at', models.DateTimeField(blank=True, help_text='EXIF timestamp or upload time', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phase', models.CharField(blank=True, help_text='Project phase when photo was taken', max_length=100, null=True)),
                ('category', models.CharField(choices=[('PROGRESS', 'Progress'), ('BEFORE', 'Before'), ('AFTER', 'After'), ('DEFICIENCY', 'Deficiency'), ('DELIVERY', 'Delivery'), ('INSPECTION', 'Inspection'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='PROGRESS', max_length=20)),
                ('ai_tags', models.JSONField(blank=True, default=list, help_text='Auto-generated AI categories')),
                ('is_client_visible', models.BooleanField(default=True)),
                ('annotations', models.JSONField(blank=True, help_text='Markup data: arrows, text, highlights (canvas overlay JSON)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_daily_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='field_ops.dailylog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'documents_photo',
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_auto_generated', models.BooleanField(default=False, help_text='AI-created album')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='documents.photo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('photos', models.ManyToManyField(blank=True, related_name='albums', to='documents.photo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_albums', to='projects.project')),
            ],
            options={
                'verbose_name': 'Photo Album',
                'verbose_name_plural': 'Photo Albums',
                'db_table': 'documents_photo_album',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfi_number', models.IntegerField(help_text='Auto-incremented per project')),
                ('subject', models.CharField(max_length=300)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=10)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('schedule_impact_days', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('distribution_list', models.ManyToManyField(blank=True, help_text='Users who receive RFI answer notifications', related_name='rfi_distributions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFI',
                'verbose_name_plural': 'RFIs',
                'db_table': 'documents_rfi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submittal_number', models.IntegerField(help_text='Auto-incremented per project')),
                ('title', models.CharField(max_length=300)),
                ('spec_section', models.CharField(blank=True, help_text='CSI specification section reference', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('APPROVED_AS_NOTED', 'Approved As Noted'), ('REVISE_RESUBMIT', 'Revise & Resubmit'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=25)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='submittals', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals', to='projects.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submittals_reviewing', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submittals_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submittal',
                'verbose_name_plural': 'Submittals',
                'db_table': 'documents_submittal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Acknowledgment',
                'verbose_name_plural': 'Document Acknowledgments',
                'db_table': 'documents_acknowledgment',
                'ordering': ['-acknowledged_at'],
                'indexes': [models.Index(fields=['document', 'user'], name='docs_ack_doc_user_idx')],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['organization', 'project'], name='docs_folder_org_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['organization', 'parent'], name='docs_folder_org_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'project', 'status'], name='docs_doc_org_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'folder'], name='docs_doc_org_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'is_current_version'], name='docs_doc_org_current_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'is_current_version'], name='docs_doc_proj_current_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['organization', 'project', 'category'], name='docs_photo_org_proj_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['organization', 'project', '-taken_at'], name='docs_photo_org_proj_taken_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['organization', 'is_client_visible'], name='docs_photo_org_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['project', 'linked_daily_log'], name='docs_photo_proj_log_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['organization', 'project'], name='docs_album_org_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='rfi',
            index=models.Index(fields=['organization', 'project', 'status'], name='docs_rfi_org_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rfi',
            index=models.Index(fields=['organization', 'project', 'priority'], name='docs_rfi_org_proj_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='rfi',
            index=models.Index(fields=['organization', 'assigned_to'], name='docs_rfi_org_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='rfi',
            index=models.Index(fields=['project', 'rfi_number'], name='docs_rfi_proj_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfi',
            constraint=models.UniqueConstraint(fields=('project', 'rfi_number'), name='unique_rfi_number_per_project'),
        ),
        migrations.AddIndex(
            model_name='submittal',
            index=models.Index(fields=['organization', 'project', 'status'], name='docs_sub_org_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submittal',
            index=models.Index(fields=['organization', 'reviewer'], name='docs_sub_org_reviewer_idx'),
        ),
        migrations.AddIndex(
            model_name='submittal',
            index=models.Index(fields=['project', 'submittal_number'], name='docs_submittal_proj_num_idx'),
        ),
        migrations.AddConstraint(
            model_name='submittal',
            constraint=models.UniqueConstraint(fields=('project', 'submittal_number'), name='unique_submittal_number_per_project'),
        ),
    ]
