# Generated by Django 5.2.11 on 2026-02-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_expand_project_add_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionitem',
            new_name='projects_ac_organiz_c100fb_idx',
            old_name='projects_ai_org_resolved_idx',
        ),
        migrations.RenameIndex(
            model_name='actionitem',
            new_name='projects_ac_organiz_598509_idx',
            old_name='projects_ai_org_proj_res_idx',
        ),
        migrations.RenameIndex(
            model_name='actionitem',
            new_name='projects_ac_assigne_cf26a3_idx',
            old_name='projects_ai_assign_res_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='projects_ac_organiz_21dec4_idx',
            old_name='projects_al_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='projects_ac_project_9cc7b7_idx',
            old_name='projects_al_proj_created_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='projects_ac_user_id_9dc685_idx',
            old_name='projects_al_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_8941e0_idx',
            old_name='projects_pr_organiz_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_ee9523_idx',
            old_name='projects_pr_organiz_type_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_7d8536_idx',
            old_name='projects_pr_organiz_created_idx',
        ),
        migrations.RenameIndex(
            model_name='projectstagetransition',
            new_name='projects_pr_project_1d007a_idx',
            old_name='projects_tr_proj_created_idx',
        ),
    ]
