# Generated by Django 5.2.12 on 2026-03-05 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectstagetransition',
            name='from_status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('site_survey', 'Site Survey'), ('proposal', 'Proposal'), ('acceptance', 'Acceptance'), ('in_progress', 'In Progress'), ('milestones', 'Milestones'), ('finish_project', 'Finish Project'), ('billing', 'Billing'), ('paid_complete', 'Paid / Complete'), ('canceled', 'Canceled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectstagetransition',
            name='to_status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('site_survey', 'Site Survey'), ('proposal', 'Proposal'), ('acceptance', 'Acceptance'), ('in_progress', 'In Progress'), ('milestones', 'Milestones'), ('finish_project', 'Finish Project'), ('billing', 'Billing'), ('paid_complete', 'Paid / Complete'), ('canceled', 'Canceled')], max_length=30),
        ),
    ]
