# Generated by Django 5.2.11 on 2026-02-18 04:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_alter_contact_options_and_more'),
        ('projects', '0003_rename_projects_ai_org_resolved_idx_projects_ac_organiz_c100fb_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/%Y/')),
                ('primary_color', models.CharField(default='#2563EB', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', help_text='Hex color code', max_length=7)),
                ('company_name_override', models.CharField(blank=True, help_text='Override org name shown in portal (optional)', max_length=200, null=True)),
                ('welcome_message', models.TextField(blank=True, default='Welcome to your project portal. Track progress, approve selections, and stay connected.')),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain for white-label portal (e.g., portal.yourcompany.com)', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Portal Branding',
                'verbose_name_plural': 'Portal Branding',
                'db_table': 'clients_portal_branding',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('FLOORING', 'Flooring'), ('COUNTERTOPS', 'Countertops'), ('CABINETS', 'Cabinets'), ('FIXTURES', 'Fixtures'), ('PAINT', 'Paint'), ('TILE', 'Tile'), ('HARDWARE', 'Hardware'), ('APPLIANCES', 'Appliances'), ('LIGHTING', 'Lighting'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLIENT_REVIEW', 'Client Review'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('INSTALLED', 'Installed')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to_client', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='projects.project')),
            ],
            options={
                'verbose_name': 'Selection',
                'verbose_name_plural': 'Selections',
                'db_table': 'clients_selections',
                'ordering': ['sort_order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='SelectionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('price_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price delta vs. standard/base option (can be negative)', max_digits=14)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='selections/%Y/%m/')),
                ('spec_sheet_url', models.URLField(blank=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='clients.selection')),
            ],
            options={
                'verbose_name': 'Selection Option',
                'verbose_name_plural': 'Selection Options',
                'db_table': 'clients_selection_options',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='selection',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_selections', to='clients.selectionoption'),
        ),
        migrations.CreateModel(
            name='ClientApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_type', models.CharField(choices=[('CHANGE_ORDER', 'Change Order'), ('SELECTION', 'Selection Approval'), ('DRAW_REQUEST', 'Draw Request'), ('DESIGN_MODIFICATION', 'Design Modification'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('client_signature', models.JSONField(blank=True, help_text='Signature data: {name, ip, user_agent, signed_at, image_data}', null=True)),
                ('reminded_count', models.IntegerField(default=0)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_approvals', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_approvals', to='projects.project')),
            ],
            options={
                'verbose_name': 'Client Approval',
                'verbose_name_plural': 'Client Approvals',
                'db_table': 'clients_approvals',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['organization', 'project', 'status'], name='clients_app_organiz_4de80b_idx'), models.Index(fields=['organization', 'project', 'approval_type'], name='clients_app_organiz_3d219f_idx'), models.Index(fields=['organization', 'status', 'expires_at'], name='clients_app_organiz_351dce_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('CLIENT', 'Client')], max_length=12)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of S3 file keys or document IDs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='projects.project')),
                ('sender_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_messages_sent', to='crm.contact')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Message',
                'verbose_name_plural': 'Client Messages',
                'db_table': 'clients_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'project', '-created_at'], name='clients_mes_organiz_1285e8_idx'), models.Index(fields=['organization', 'project', 'is_read'], name='clients_mes_organiz_b31d8d_idx'), models.Index(fields=['sender_type'], name='clients_mes_sender__691b71_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(help_text="Portal login email — may differ from contact's primary email", max_length=254)),
                ('pin_code', models.CharField(blank=True, help_text='Optional 4-6 digit PIN for extra portal security', max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Granular permissions: view_photos, view_schedule, view_documents, make_payments, approve_selections, send_messages')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_accesses', to='projects.project')),
            ],
            options={
                'verbose_name': 'Client Portal Access',
                'verbose_name_plural': 'Client Portal Accesses',
                'db_table': 'clients_portal_access',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'project'], name='clients_por_organiz_f1ba7b_idx'), models.Index(fields=['organization', 'contact'], name='clients_por_organiz_94a91b_idx'), models.Index(fields=['access_token'], name='clients_por_access__f790a0_idx'), models.Index(fields=['email'], name='clients_por_email_89b203_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'contact', 'project'), name='unique_client_portal_access_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ClientSatisfactionSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.CharField(blank=True, help_text="Which milestone triggered this survey (e.g., 'Framing Complete')", max_length=200)),
                ('rating', models.IntegerField(help_text='Overall satisfaction 1–10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nps_score', models.IntegerField(blank=True, help_text='Net Promoter Score 0–10 (would you recommend us?)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to='projects.project')),
            ],
            options={
                'verbose_name': 'Satisfaction Survey',
                'verbose_name_plural': 'Satisfaction Surveys',
                'db_table': 'clients_satisfaction_surveys',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['organization', 'project'], name='clients_sat_organiz_7d4dbc_idx'), models.Index(fields=['organization', 'contact'], name='clients_sat_organiz_0f3ed0_idx'), models.Index(fields=['organization', '-submitted_at'], name='clients_sat_organiz_790413_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='selectionoption',
            index=models.Index(fields=['selection', 'sort_order'], name='clients_sel_selecti_4ba700_idx'),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['organization', 'project', 'status'], name='clients_sel_organiz_d4d0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['organization', 'project', 'category'], name='clients_sel_organiz_8cb414_idx'),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['project', 'sort_order'], name='clients_sel_project_71275f_idx'),
        ),
    ]
