# Generated by Django 5.2.11 on 2026-02-18 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0002_rename_estimating_assembly_org_created_estimating__organiz_986649_idx_and_more'),
        ('projects', '0003_rename_projects_ai_org_resolved_idx_projects_ac_organiz_c100fb_idx_and_more'),
        ('scheduling', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='crew',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='crew',
            name='trade',
            field=models.CharField(choices=[('general', 'General'), ('framing', 'Framing'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('painting', 'Painting'), ('flooring', 'Flooring'), ('roofing', 'Roofing'), ('concrete', 'Concrete'), ('drywall', 'Drywall'), ('finish_carpentry', 'Finish Carpentry'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('equipment_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight-Line'), ('declining_balance', 'Declining Balance')], default='straight_line', max_length=20)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='projects.project')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('milestone', 'Milestone'), ('phase', 'Phase'), ('summary', 'Summary')], default='task', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('canceled', 'Canceled')], default='not_started', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=1)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_critical_path', models.BooleanField(default=False)),
                ('float_days', models.IntegerField(default=0)),
                ('early_start', models.DateField(blank=True, null=True)),
                ('early_finish', models.DateField(blank=True, null=True)),
                ('late_start', models.DateField(blank=True, null=True)),
                ('late_finish', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('wbs_code', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='scheduling.crew')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('cost_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='estimating.costcode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='scheduling.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('finish_to_start', 'Finish-to-Start (FS)'), ('start_to_start', 'Start-to-Start (SS)'), ('finish_to_finish', 'Finish-to-Finish (FF)'), ('start_to_finish', 'Start-to-Finish (SF)')], default='finish_to_start', max_length=20)),
                ('lag_days', models.IntegerField(default=0)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_deps', to='scheduling.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_deps', to='scheduling.task')),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleTask',
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='sched_equipment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='sched_task_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'is_critical_path'], name='sched_task_proj_cp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('predecessor', 'successor')},
        ),
    ]
