# Generated by Django 5.2.11 on 2026-02-18 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_expand_crm_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_organiz_bb9bc1_idx',
            old_name='crm_contact_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_organiz_536890_idx',
            old_name='crm_contact_org_score_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_organiz_5cf4ad_idx',
            old_name='crm_contact_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='crm_interac_organiz_65c5e5_idx',
            old_name='crm_interact_org_contact_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='crm_interac_organiz_edd4a8_idx',
            old_name='crm_interact_org_lead_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_organiz_aafa0f_idx',
            old_name='crm_lead_org_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_organiz_347d31_idx',
            old_name='crm_lead_org_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_organiz_b86643_idx',
            old_name='crm_lead_org_contacted_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_organiz_608428_idx',
            old_name='crm_lead_org_followup_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pipeline_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.pipelinestage'),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterModelTable(
            name='lead',
            table=None,
        ),
    ]
