# Generated by Django 5.2.12 on 2026-03-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_two_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
    ]
