# Generated by Django 5.2.11 on 2026-02-18 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_v2'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certifiedpayrollreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prevailingwagerate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certifiedpayrollreport',
            name='compliance_issues',
            field=models.JSONField(blank=True, default=list, help_text='[{employee_id, trade, hours, paid_rate, required_rate, shortfall}]'),
        ),
        migrations.AlterField(
            model_name='certifiedpayrollreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='certifiedpayrollreport',
            name='generated_file_key',
            field=models.CharField(blank=True, help_text='S3 key for the generated PDF.', max_length=500),
        ),
        migrations.AlterField(
            model_name='certifiedpayrollreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='burden_rate',
            field=models.DecimalField(decimal_places=4, default='0.2800', help_text='Burden rate as decimal (e.g., 0.28 = 28% of base for benefits/insurance/taxes).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='[{name, number, expiry, issuing_body}]'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='direct_deposit_accounts',
            field=models.JSONField(blank=True, default=list, help_text='[{bank_name, routing_number, account_number_last4, allocation_pct}]'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict, help_text='{name, relationship, phone}'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default='1.50', help_text='Overtime multiplier (e.g., 1.5 for time-and-a-half).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='double_time_hours',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='federal_tax',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='fica',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='job_cost_allocations',
            field=models.JSONField(blank=True, default=list, help_text='[{project_id, cost_code_id, hours, amount}]'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='medicare',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='regular_rate',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='state_tax',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='prevailingwagerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='prevailingwagerate',
            name='fringe_rate',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='prevailingwagerate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
    ]
